name: Top Random tip

on:
  schedule:
    - cron: "30 16 * * 2"
  workflow_dispatch:

jobs:
  build:
    name: Tweet random tip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn install
      - name: Run Twitter bot
        run: yarn twitter:tip
        env:
          AIRTABLE_API_BASE: ${{ secrets.AIRTABLE_API_BASE }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
